version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install fontbakery
          command: pip install fontbakery
      - run:
          name: run fontbakery tests

          command: |
            cd fonts/ttf
            fontbakery check-googlefonts -n -l WARN -x com.google.fonts/check/ftxvalidator *.ttf

workflows:
  launch:
    jobs:
      - build
