version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
  
    working_directory: ~/repo

    steps:
          - checkout
          - run:
              name: install fontbakery
              command: pip install fontbakery
          - run:
              name: run fontbakery tests

              command: |
              cd ttfs
              fontbakery check-googlefonts *.ttf 
            
workflows:
  launch:
    jobs:
      - build