version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install fontbakery
          command: pip install fontbakery
      - run:
          name: install ttfautohint
          command: |
            sudo apt-get update
            sudo apt-get install ttfautohint
      - run:
          name: run static fontbakery tests
          command: |
            cd fonts/ttf
            fontbakery check-googlefonts -n -l FAIL -x com.google.fonts/check/ftxvalidator *.ttf
      - run:
          name: run variable fontbakery tests
          command: |
            cd fonts/gfvariable
            fontbakery check-googlefonts -n -l FAIL -x com.google.fonts/check/ftxvalidator *.ttf

workflows:
  Fontbakery Checks:
    jobs:
      - build
