version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
          - checkout
          - run:
              name: install fontbakery
              command: pip install fontbakery
          - run:
              name: run fontbakery tests

              command: |
                cd fonts
                fontbakery check-googlefonts -n -l WARN *.ttf
            
workflows:
  launch:
    jobs:
      - build